//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public int Employee_ID { get; set; }
        public string Full_Name { get; set; }
        public string Job { get; set; }
        public Nullable<int> Job_Degree { get; set; }
        public Nullable<int> Job_Stage { get; set; }
        public string Graduate { get; set; }
        public string Place_of_Graduate { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> First_job_Date { get; set; }
        public string Department { get; set; }
        public string Class { get; set; }
        public Nullable<int> Working_Years { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string Place_Of_working { get; set; }
        public string leveles { get; set; }
    
        public virtual Table_1 Table_11 { get; set; }
        public virtual Table_1 Table_12 { get; set; }
        public virtual Table_2 Table_2 { get; set; }
    }
}
